par(mfrow=c(2,2))
plot(x=HPC2007$DateTime,y=HPC2007$Global_active_power,type='l',ylab="Global Active Power (kilowatts)",xlab="")
plot(x=HPC2007$DateTime,y=HPC2007$Voltage,type='l',ylab="Voltage",xlab="datetime")
plot(x=HPC2007$DateTime,y=HPC2007$Sub_metering_1,type='l',col='black',ylab="Energy sub metering",xlab="")
lines(x=HPC2007$DateTime,y=HPC2007$Sub_metering_2,col="red")
lines(x=HPC2007$DateTime,y=HPC2007$Sub_metering_3,col="blue")
legend('topright',col=c("black","red","blue"),names(HPC2007[,7:9]),lty=1)
plot(x=HPC2007$DateTime,y=HPC2007$Global_reactive_power,type='l',ylab="Global_reactive_power", xlab="datetime")
dev.copy(device=png,file="plot4.png",height=480,width=480)
dev.off()